FROM node:18

USER root
WORKDIR /app


# Install Python and flake8
RUN apt-get update && \
    npm install -g eslint && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./backend .
COPY ./frontend/app.js .
COPY ./frontend/styles.css .

