FROM node:18

USER root

WORKDIR /app

# Install Python and flake8
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint && \
    chmod +x /usr/local/bin/hadolint  && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .

